### ISSUE TITLE
Gambling feature

### ISSUE THREAD

**Issue by AZFire1** [aesthetic-org/bot#21] opened 2021-07-14 00:46 UTC
**Is your feature request related to a problem? Please describe.**
It is not. Once an economy system exists, add a gambling feature but add a command that allows you to rig it for yourself.

Describe the solution you'd like
N/A

Describe alternatives you've considered
N/A

Additional context
N/A

**Comment by frenchbones** [comment] 2021-07-14 01:03
Duplicate of #18 
It is included in the slots and is going to be the only way to gamble

**Closed by frenchbones** 2021-07-14 01:03 UTC
Labels: duplicate
